#!/bin/sh -e

# make an object file from a raw binary firmware file
# arguments:
#   1 - firmware file
#   2 - output file
#   3 - template output file (used to learn desired format)

bfdname=`objdump -f ${3} | grep -e "${3}:" | sed "s/.*file format \(.*\)/\1/"`
bfdarch=`objdump -f ${3} | grep -e "architecture:" | sed "s/.*ture: \(.*\),.*/\1/"`

objcopy -I binary ${1} -B ${bfdarch} -O ${bfdname} ${2} --rename-section .data=.rodata,alloc,load,data,contents,readonly
